Update WebpageTesting_workflow.yml

diff --git a/.github/workflows/WebpageTesting_workflow.yml b/.github/workflows/WebpageTesting_workflow.yml
--- a/.github/workflows/WebpageTesting_workflow.yml
+++ b/.github/workflows/WebpageTesting_workflow.yml
@@ -48,7 +48,7 @@ jobs:
       run: dotnet build EpamWebTests/EpamWebTests.sln --no-restore
       
     - name: Check Network Connectivity
-      run: ping www.epam.com
+      run: timeout 30s ping -c 4 www.epam.com || echo "Ping failed or timed out"
 
     - name: Run Playwright Tests
       run: dotnet test EpamWebTests/EpamWebTests.csproj --configuration Release --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory ${{ github.workspace }}/allure-results 
