Update WebpageTesting_workflow.yml

diff --git a/.github/workflows/WebpageTesting_workflow.yml b/.github/workflows/WebpageTesting_workflow.yml
--- a/.github/workflows/WebpageTesting_workflow.yml
+++ b/.github/workflows/WebpageTesting_workflow.yml
@@ -47,11 +47,12 @@ jobs:
     - name: Build the project
       run: dotnet build EpamWebTests/EpamWebTests.sln --no-restore
       
-    - name: Check Network Connectivity
-      run: timeout 30s ping -c 4 www.epam.com || echo "Ping failed or timed out"
+    - name: Test HTTP Connectivity to EPAM
+      run: curl -Is https://www.epam.com/ || echo "HTTP request to EPAM failed"
+    
+    - name: Test HTTP Connectivity to Facebook
+      run: curl -Is https://www.facebook.com/ || echo "HTTP request to Facebook failed"
 
-    - name: Check Network Connectivity
-      run: timeout 30s ping -c 4 www.facebook.com || echo "Ping failed or timed out"
 
     - name: Run Playwright Tests
       run: dotnet test EpamWebTests/EpamWebTests.csproj --configuration Release --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory ${{ github.workspace }}/allure-results 
